version: '3'
services:
 
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - backend
 
  microservice:
    depends_on:
      - mongodb
    image: go-docker-optimized:latest
    environment:
      - PORT=9090
    environment:
      - MGOHOSTNAME=mongodb
    ports: 
      - "9090:9090"
    links: 
      - mongodb
    networks:
      - backend
  
volumes:
   mongodata:
    
networks:
  backend:
    driver: "bridge"